// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB32sWrwwhnnLSB-cDiEsH3KPZGCMZxUO4',
    appId: '1:633772500582:web:39159db3958d34ab482fa7',
    messagingSenderId: '633772500582',
    projectId: 'demodataadminapp',
    authDomain: 'demodataadminapp.firebaseapp.com',
    storageBucket: 'demodataadminapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOqS-3FPmGZ6iqzM5LiYtuoGW61g3_Usg',
    appId: '1:633772500582:android:5db87b384a0bc4a8482fa7',
    messagingSenderId: '633772500582',
    projectId: 'demodataadminapp',
    storageBucket: 'demodataadminapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi0a6DWFFsPB4W2T_LuavRddMinoRg2ro',
    appId: '1:633772500582:ios:18930283f3fade80482fa7',
    messagingSenderId: '633772500582',
    projectId: 'demodataadminapp',
    storageBucket: 'demodataadminapp.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi0a6DWFFsPB4W2T_LuavRddMinoRg2ro',
    appId: '1:633772500582:ios:18930283f3fade80482fa7',
    messagingSenderId: '633772500582',
    projectId: 'demodataadminapp',
    storageBucket: 'demodataadminapp.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB32sWrwwhnnLSB-cDiEsH3KPZGCMZxUO4',
    appId: '1:633772500582:web:7d5f830f8567ab48482fa7',
    messagingSenderId: '633772500582',
    projectId: 'demodataadminapp',
    authDomain: 'demodataadminapp.firebaseapp.com',
    storageBucket: 'demodataadminapp.firebasestorage.app',
  );
}
